### PR TITLE
review: fix CI on windows

### LINKED ISSUE #273: Add support for Windows
There are some tests that do not pass on Windows because of the difference between file paths in windows and linux. For example, `sorald.processor.ProcessorTest`.

* [ ] fix the tests on Windows
* [ ] add Windows CI

### PR DESCRIPTION
**Pull request by MartinWitt**
Classical first PR trying to fix the CI on Windows.  The problems seems that the filename is simply the absolute path and not the relative path. How on earth this works on Unix is unknown to me. 
Fixes #273

### CODE REVIEW

**Comment by algomaster99** [comment]
We are replacing `RuleVerifier` with [`SonarLintEngine`](https://github.com/SpoonLabs/sorald/pull/696/files#diff-7bae8e494b540a76e6d87048c0089e595e1ae162fb8faf8751acab79224095d3) in #696 . Once that refactoring PR is done, I think we can work on fixing the CI on Windows.

Moreover, the general way to fix this is to use `Path` instead of `String`. See https://github.com/SpoonLabs/sorald/issues/166. I believe this way we shall be able to support Sorald independent of the file system.

**Comment by algomaster99** [comment]
@MartinWitt now you may continue to work on this. We have refactored the infrastructure of the project. See #696.

**Comment by MartinWitt** [comment]
Works 👍 
https://github.com/SpoonLabs/sorald/blob/c9db9ffac490b0d72ee13abe6ab1ae1794341fe2/src/main/java/sorald/FileUtils.java#L132 You may want to remove this last artifact of windows, the File API can handle Unix style paths on windows.

**Comment by algomaster99** [comment]
> You may want to remove this last artefact of windows, the File API can handle Unix style paths on windows.

@MartinWitt It is just not handling path format, but also storing the jar plugin in the conventionally accepted cache directory of Windows which now I realise is not correct. It should be something like this - `C:\Users\HP-JVF78\AppData\Local\aman\sorald\Cache\`.

I guess we can merge this PR regardless your suggested change?

**Comment by algomaster99** [comment]
I am also surprised that the tests pass as is. I wonder why it was disabled before.

**Comment by MartinWitt** [comment]
> I guess we can merge this PR regardless of your suggested change?

Yes absolutely the path is a simple style issue. And as it seems there are more problems, we should split this in a separate PR.

> I am also surprised that the tests pass as is. I wonder why it was disabled before.

I was surprised too.

**Review by algomaster99 — APPROVED** [review]
Thanks @MartinWitt !

**Comment by algomaster99** [comment]
@MartinWitt If we have official support for Windows now, should we also update the README badge?

**Comment by MartinWitt** [comment]
Yes, the badge and the README text about platform support.

**Comment by algomaster99** [comment]
Could you submit a PR for that?

**Comment by MartinWitt** [comment]
Yes I will create one.

**Pull request merged**
