### PR TITLE
feat: add checks which were assumed to be deprecated

### PR DESCRIPTION
**Pull request by algomaster99**
There were [some rules](https://github.com/SpoonLabs/sorald/issues/713#issuecomment-1064957430) that were not reported by Sorald because their `Check` was not an entry in `sorald.sonar.Checks`. This was done because we assumed that `DeprecatedRuleKey` would mean that the rule itself has been deprecated. However, it means that the _key_ corresponding to the rule has been deprecated. In other words, the key of a said rule has been updated.

The rules reported by @NiklasWicklund [here](https://github.com/SpoonLabs/sorald/issues/713#issuecomment-1064957430) were not being reported because we had disabled them.

### CODE REVIEW

**Comment by algomaster99** [comment]
There are approximately 45 more rules which are not configured in `Checks.java`. Maybe we can add them all. @slarse @khaes-kth is there a script to generate [all the maps](https://github.com/SpoonLabs/sorald/blob/86363a1f745c69339c3cc3d7d0efbacb9f6ba37e/src/main/java/sorald/sonar/Checks.java#L131) defined in that file?

**Comment by algomaster99** [comment]
I added tests to confirm that those violations are reported now.

**Comment by khaes-kth** [comment]
Thanks for documenting taking care of this Aman. I am not aware of the script you are looking for.

I just wanted to know if this significantly affects our results in the paper. Can you assess how many new violations are detected after adding these checks? Currently, we report that "The total number of violations of all 97 fixable and partially fixable bug rules in our dataset is 4,928." This number is extracted from the mining `stats.json` file.

**Comment by algomaster99** [comment]
@khaes-kth these rules are code smells. I don't think they should affect the rules. Moreover, if we do a manual analysis of code smell rules as well, these 3 rules would be unfixable.

**Comment by algomaster99** [comment]
> I am not aware of the script you are looking for.

I am sorry I forgot to respond to this. I mean the maps [here](https://github.com/SpoonLabs/sorald/blob/86363a1f745c69339c3cc3d7d0efbacb9f6ba37e/src/main/java/sorald/sonar/Checks.java#L131-L672). I am pretty sure they are not maintained manually.

**Comment by algomaster99** [comment]
@NiklasWicklund, you can now build the latest version on `master` to run your experiments.

**Pull request merged**
