### PR TITLE
chore: Add SonarCloud config

### PR DESCRIPTION
**Pull request by slarse**
Carbon copy of #464, but the head is in the SpoonLabs/Sorald repo instead of my personal fork.

### CODE REVIEW

**Comment by monperrus** [comment]
Per our conversation, we want to merge this but we don't want comment to posted, we want only the Github PR status check.

**Comment by slarse** [comment]
Test failures probably due to GHA backend trouble: https://www.githubstatus.com/

**Comment by slarse** [comment]
@monperrus This is now ready for merge.

I've disabled PR comments in the SonarCloud UI, so we'll see if it honors that.

Note that the PR status check will _not_ be posted on PRs that originate from forks, due to the security implications we discussed earlier. This seems to be something of an unsolved problem for SonarCloud, see e.g. [this SO post](https://stackoverflow.com/a/48822979) and the fact that the Travis plugin [has it as an upcoming feature](https://docs.travis-ci.com/user/sonarcloud/#upcoming-improvements).

We can work around that by our members working within the repository instead of on private forks, but external contributors won't have their code vetted by SonarCloud.

**Comment by fermadeiral** [comment]
LGTM.

**Comment by slarse** [comment]
@fermadeiral feel free to merge!

**Comment by fermadeiral** [comment]
Ok! Thank you, @slarse!

**Comment by monperrus** [comment]
great milestone, thanks!

**Pull request merged**
