### PR TITLE
chore: parse SonarJava plugin URL from config

### LINKED ISSUE #718: Read SonarLint url from a config file
It is better to save the [SonarLing url](https://github.com/SpoonLabs/sorald/pull/696/files#diff-7bae8e494b540a76e6d87048c0089e595e1ae162fb8faf8751acab79224095d3R52) in a config file and then make our python script check if the correct version is being downloaded by checking the config file.

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #718

### CODE REVIEW

**Review by khaes-kth — APPROVED** [review]
LGTM!

Thanks @algomaster99

**Comment by khaes-kth** [comment]
Also, can you make it a draft PR until it is ready for merge?

**Comment by algomaster99** [comment]
> There is still a test failure. Can you fix it?

I will look into this. I am not sure why the tests are failing. It works on my local. :thinking:

**Comment by algomaster99** [comment]
@khaes-kth I think this is ready for merge.  The coverage is less because of catch blocks and a utility class I added to read the config file.

**Review by khaes-kth — APPROVED** [review]
Approved :)

**Pull request merged**
