### PR TITLE
refactor: restructure project to load Sorald as a service using Java SPI

### PR DESCRIPTION
**Pull request by algomaster99**
@MartinWitt, thanks for your work, first of all. It is a great milestone toward integrating the Qodana static analyzer and development in general, as the code quality has definitely increased.

Let's work towards merging this now because there is feature request #807 that require a lot of code movement. I feel it is better to start working on top of the changes in this PR to avoid dealing with merge conflicts later. Some things that need to be done before we merge this PR:
- [x] Update usage in README #810 
- [x] What do we do about the [docs](https://github.com/SpoonLabs/sorald/tree/spi/docs)? Most files are related to `sorald` and not `sorald-parent`. Should we move it? I am in favour of letting them be for two reasons: #809 
  - `docs` should be accessible from the root of the repository
  - There is no immediate need to do so.
- [ ] Your final review of the changes you have made. I hope I have not messed them up during merging from `master`.

@MartinWitt , please give your opinions about subtasks 2 and 3. Once all of them are resolved, we can proceed to merge. Note that this PR will **not** be squashed as each commit is an atomic change in itself.

### CODE REVIEW

**Comment by algomaster99** [comment]
Merging this PR as it is needed to implement some requested features. I have fixed whatever was necessary. I have not tested the deployment of SNAPSHOT version and it may fail, but I don't have access to its credentials as of now. However, @monperrus , @slarse, and I have had a discussion over this. If there is a need to revoke the tokens, I will create an OSSRH account chains-bot with email [chains@eecs.kth.se](mailto:chains@eecs.kth.se).

**Comment by algomaster99** [comment]
Thanks for your work, @MartinWitt ! It is an advancement towards the integration of the Qodana static analyzer.

**Comment by monperrus** [comment]
Yes! Thanks @MartinWitt

**Comment by monperrus** [comment]
> I will create an OSSRH account chains-bot with email [chains@eecs.kth.se](mailto:chains@eecs.kth.se)

excellent initiative :+1:

**Pull request merged**
