### PR TITLE
experiment: Add initial record for verificatum/verificatum-vmn PR 13

### PR DESCRIPTION
**Pull request by slarse**
Another PR for Verificatum. This is the initial record (i.e. PR is not yet merged). You can find the PR by looking at the `prMetadata` section of the record.

### CODE REVIEW

**Comment by slarse** [comment]
@monperrus As each Verificatum PR is something of a mini-milestone, I'll assign you as a reviewer on the records to keep you up-to-date.

**Comment by monperrus** [comment]
Thanks.

Note that Douglas has asked to get PRs by batch (say at least 5 fixes in a single PR).

**Comment by slarse** [comment]
Last I spoke to him, he asked to get PRs with all fixes for a single rule. There were only 3 violations of this rule, I repaired them all.

**Comment by monperrus** [comment]
OK, could you ping him with a personal email? Thanks!

**Comment by slarse** [comment]
> OK, could you ping him with a personal email? Thanks!

Yep. I'll also confirm again how he wants the PRs.

**Pull request merged**
