### PR TITLE
break: Remove Git patch generation

### PR DESCRIPTION
**Pull request by slarse**
#409 

Breaking change that removes the Git patch generation functionality. Since we have in-place repair, this feature is redundant. We can currently achieve roughly the same behavior like so:

```bash
# in some Git repo
$ sorald repair --file-output-strategy IN_PLACE [... options ...]
$ git diff > sorald_repair.patch
```

The only difference is that we don't get one patch file per changed source file, but I really don't see why we'd want that either (and it could be done with some more scripting).

### CODE REVIEW

**Comment by fermadeiral** [comment]
@slarse, this feature was implemented by @henry-lp, and before anything else I would like to hear from him.

@henry-lp, if this feature is removed, does something get broken on the Repairnator side?

**Comment by slarse** [comment]
@fermadeiral It does break repairnator (see https://github.com/eclipse/repairnator/blob/0cff4102b6792fe209d6f890589364dfb3bfa014/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/Sorald.java), but it can be fixed by using in-place repair instead. Right now, Sorald is essentially used like this:

1. Perform patch out-of-place.
2. Generate patches.
3. Apply patches to repo.

That can be cut down to.

1. Perform patch in-place.

There's one extra thing in that Sorald "notifies" something (a listener I presume?) about the individual patch files, of which I don't quite know the purpose.

@henry-lp Feel free to correct me if I'm wrong.

**Comment by slarse** [comment]
Note also that we're removing out-of-place repair as well to make it possible to improve other features. And Repairnator also uses the old camel case version of the CLI. So already, the usage in Repairnator needs to be patched, but it's all easy fixes.

**Comment by slarse** [comment]
@fermadeiral Regardless of what @henry-lp answers, we can defer a decision on this PR until the next meeting (on the 9th).

**Comment by fermadeiral** [comment]
@slarse thanks.

**Comment by slarse** [comment]
@fermadeiral According to @khaes-kth , we don't need the built-in Git patch generation:

https://github.com/SpoonLabs/sorald/issues/409#issuecomment-791405658

**Comment by fermadeiral** [comment]
@slarse, if nothing will be broken on Repairnator, I'm merging.

**Comment by slarse** [comment]
@fermadeiral That's not quite what we meant, Repairnator integration is already broken by the updates to the CLI. We need to patch Repairnator with the new functionality, but it's not hard, and will simplify the code overall. We'll discuss this during the next meeting, it'll be up to myself and @khaes-kth to make it work :)

**Comment by slarse** [comment]
So, to be clear, it _is_ currently used, but it doesn't actually need to be used.

**Comment by khaes-kth** [comment]
> So, to be clear, it _is_ currently used, but it doesn't actually need to be used.

Agree!

**Comment by fermadeiral** [comment]
@slarse thank you for the clarification.

In this case, do we already have an issue somewhere for us to not forget that Repairnator is broken because of several changes in Sorald and so we need to fix it?

**Comment by slarse** [comment]
I think my clarification wasn't that clear. Repairnator, right now, isn't broken. It's just using an older version of Sorald. Once someone updates the version of Sorald in Repairnator, they'll also have to deal with the changes in the CLI. To me, that's just common sense when updating a dependency; check for changes and make sure that it works.

While we _could_ be "nice" and open an issue in Repairnator about it, I don't think it's a good idea to set a precedent that we notify dependents of such changes, as that's something we may forget to do at another time. WDYT?

**Comment by fermadeiral** [comment]
> I think my clarification wasn't that clear.

Indeed, because "Repairnator integration is already broken by the updates to the CLI" is very different from "Repairnator, right now, isn't broken".

But I got your point now, and I agree with you. No issue to be created in Repairnator.

**Pull request merged**
