### PR TITLE
refactor(2095): Refactor UnclosedResourcesProcessor

### LINKED ISSUE #540: Processor for S2095 (UnclosedResources) introduces new resource leak
In the following code there is a resource leak for `bw2`:

```java
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

class Test {
    public static void saveTo(File file1, File file2) {
        BufferedWriter bw1 = null;
        BufferedWriter bw2 = null;
        try {
            bw1 = new BufferedWriter(new FileWriter(file1));
            bw1.write("Write some stuff to file 1");

            bw2 = new BufferedWriter(new FileWriter(file2));
            bw2.write("Write some stuff to file 2");

        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            System.out.println("done");
            try {
                if (bw1 != null) {
                    bw1.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```

The processor UnclosedResourcesProcessor for S2095 seems to just remove the whole finally-block when creating the try-with-resources statement. While this behavior fixes the resource leak for `bw2` it introduces a new resource leak for `bw1` and also changes the output of the program. Here's the result:

```java
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

class Test {
    public static void saveTo(File file1, File file2) {
        BufferedWriter bw1 = null;
        try (BufferedWriter bw2 = new BufferedWriter(new FileWriter(file))) {
            bw1 = new BufferedWriter(new FileWriter(file));
            bw1.write("Write some stuff to file 1");
            bw2.write("Write some stuff to file 2");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

This is related to but different from #386 I think.

Edit: Running it one more time on the output from the previous run introduces a compile error:

```java
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

class Test {
    public static void saveTo(File file1, File file2) {
        try (BufferedWriter bw1 = new BufferedWriter(new FileWriter(file1))) {
            bw1.write("Write some stuff to file 1");
            bw2.write("Write some stuff to file 2");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

### PR DESCRIPTION
**Pull request by slarse**
I got stuck trying to fix #540 because this processor is a bit complex. This PR completely refactors the `UnclosedResourcesProcessor` to make it easier to reason about.

### CODE REVIEW

**Comment by slarse** [comment]
Coverage on diff less than 100% as some conditions never evaluate to false (for example, we don't have any case where `isAssignmentWithWriteToResolvedLocalVariable(parent)` evaluates to false). But this preserves the semantics from before the refactoring: the coverage wasn't 100% before the refactoring either.

**Comment by slarse** [comment]
Just closing/opening to try to run CI again, Codecov is failing across all projects...

**Comment by fermadeiral** [comment]
@slarse, it looks good to me.

Should I merge?

**Comment by slarse** [comment]
@fermadeiral Yes, I've verified locally that coverage is acceptable, you can take my word for it :)

**Pull request merged**
