### PR TITLE
doc: Add legacy PRs to prs.json

### PR DESCRIPTION
**Pull request by slarse**
#255 

Adds the legacy PRs from PRs_old.json to the newer prs.json file, and marks those records as legacy. This is with some minor updates to the PR recorder script.

Note that PRs_old.json is removed in this PR, as all of that data is inlined in the `sorald_statistics` attributes of the legacy records in the new `prs.json` file.

**Important:** When this PR is merged, the support workflow will open a PR for updating ACHIEVEMENTS.md. That should not be merged, as the script has not been updated to handle legacy records properly, and will claim that they are all "fully automatically generated", although we don't actually know that. I will follow up this PR with another PR to update the achievements script.

For the record, I used this one-off script to convert `PRs_old.json` records into `prs.json` records, but it's not something I want to commit to the repository.

```python
import json
import pathlib
import tempfile
import shlex
import sorald.prrecorder

PRS_JSON = pathlib.Path("experimentation/prs.json")
PRS_JSON_OLD = pathlib.Path("experimentation/PRs_old.json")

def main():
    legacy_data = json.loads(PRS_JSON_OLD.read_text("utf8"))
    for entry in legacy_data:
        owner, repo = entry["repo_slug"].split("/")
        pr_number = entry["PR_url"].split("/")[-1]

        with tempfile.TemporaryDirectory() as tmpdir:
            workdir = pathlib.Path(tmpdir)
            stats_file = workdir / "stats.json"
            stats_file.write_text(json.dumps(entry, indent=4), encoding="utf8")

            record_initial = shlex.split(f"record-initial -o {owner} -r {repo} -p {pr_number} -s {stats_file} -f {PRS_JSON}")
            sorald.prrecorder.run_cli(record_initial)

        record_final = shlex.split(f"record-final -o {owner} -r {repo} -p {pr_number} -f {PRS_JSON}")
        sorald.prrecorder.run_cli(record_final)
        
if __name__ == "__main__":
    main()
```

### CODE REVIEW

**Comment by slarse** [comment]
@monperrus I figured you could have the honor of reviewing this, as you requested it :)

**Comment by monperrus** [comment]
LGTM, thanks!

I assume that we'll have an automated PR just after merging?

**Comment by slarse** [comment]
> I assume that we'll have an automated PR just after merging?

Yes, but as I noted in the description, we don't want to merge that PR as it will be slightly incorrect. I need to also update the achievements script to look for the "legacy" tag on records. So as soon as that PR comes up, I will close it and delete the branch.

But this PR is ready to merge, so feel free to merge it :)

**Comment by slarse** [comment]
To be clear, I'll have a new PR to update the achievements generation script by the end of the day. It's not much work, I'm just busy with more pressing matters at the moment.

**Comment by monperrus** [comment]
Then let's go! Thanks for this first PR.

**Pull request merged**
