### PR TITLE
[WIP] Warning Miner added

### PR DESCRIPTION
**Pull request by khaes-kth**
Hello,

This pull request adds Warning Miner for a list of git repos.

The number of all bug warnings on [these repositories](https://github.com/FixPattern/findbugs-violations/blob/master/data/repos/repos.list) is reported [here](https://github.com/khaes-kth/sorald/blob/master/experimentation/stats/results).

The results are not finalized yet because the analysis is only finished on 170 repos (out of 730). I will commit the updated results when the analysis is finished.

Note that the rules with [these ids](https://github.com/khaes-kth/sorald/blob/master/experimentation/stats/ignored-rules) from [the documentation](https://rules.sonarsource.com/java/RSPEC-2689) are ignored because the corresponding checker does not exist in SonarQube library.

### CODE REVIEW

**Comment by fermadeiral** [comment]
Hi @khaes-kth,

Thank you for your contribution!

I had a look on the rules you are ignoring because you didn't find them in Sonar Java, and I found the checker for some of them:

2689: ObjectOutputStreamCheck
2189: NoWayOutLoopCheck
2095: UnclosedResourcesCheck
3518: DivisionByZeroCheck
3422: DependencyWithSystemScopeCheck
2222: LocksNotUnlockedCheck
3959: StreamConsumedCheck
3958: StreamNotConsumedCheck
3655: OptionalGetBeforeIsPresentCheck
3439: DefaultMessageListenerContainerCheck
3438: SingleConnectionFactoryCheck
3065: MinMaxRangeCheck
2583: ConditionalUnreachableCodeCheck
2259: NullDereferenceCheck
2637: NonNullSetToNullCheck
3546: CustomUnclosedResourcesCheck

I will take a look again on the ones that are still missing.

**Comment by khaes-kth** [comment]
Hi,

Thank you Fernanda. The way they have mentioned these rule_ids in their code is different from other ones (multi-line vs single-line). That's why I did not find them. Sorry about that.

I will run these checkers later as well and merge the data.

**Comment by khaes-kth** [comment]
The results are finalized. This PR is ready for merge.

From 730 repositories, 45 could not be analyzed, because either the repository was removed (or could not be cloned for some other reason) or Sorald threw OutOfMemory exception.

Also three of the rules that were missing and Fernanda found them were not considered because they checked XML files: DefaultMessageListenerContainerCheck, SingleConnectionFactoryCheck, DependencyWithSystemScopeCheck

176 warnings per repository on average.

**Comment by fermadeiral** [comment]
Hi, @khaes-kth.

Thanks a lot for the contribution! I would like to ask you some changes though:

- Insert an extension in the files in `experimentation/stats/` and in the files in `src/test/resources/warning_miner/`

- Put the classes `src/main/java/sorald/MineSonarWarnings.java` and `src/main/java/sorald/StatsOutputAnalyzer.java` in a new package named `src/main/java/sorald/miner/`. Change the test class `src/test/java/sorald/WarningMinerTest.java` accordingly.

A tip for next time: content like the one in `experimentation/stats/warnings` should be stored in a json format. This would save a lot of time if we need to parse the file in the future.

**Comment by khaes-kth** [comment]
Hi Fernanda,

I made your suggested changes. Do you see any other issue that should be fixed?

I will surely have your tip in mind for next PRs :)

**Comment by fermadeiral** [comment]
> Do you see any other issue that should be fixed?

No, everything is great! Thank you!

**Pull request merged**
