### PR TITLE
chore: prevent renovate from updating digests

### LINKED ISSUE #643: Renovate submitting a PR for digest update
Renovate submitted a [#624](https://github.com/SpoonLabs/sorald/pull/624) for updating `actions/checkout` to the latest commit. Let us prevent that. I configured what @slarse did [here](https://github.com/INRIA/spoon/pull/4080), but I am unsure why it wouldn't work. I found a [comment](https://github.com/renovatebot/config-help/issues/123#issuecomment-439618866) relevant to this issue. We could try it even though the comment could be dated (it was posted on Nov'18).

The [docs](https://docs.renovatebot.com/configuration-options/#enabled) are a bit unclear because the options are just written in a list, and there is no explanation of how they are nested together.

EDIT: I found the schema: https://docs.renovatebot.com/renovate-schema.json.

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #643

### CODE REVIEW

**Comment by algomaster99** [comment]
@khaes-kth ping for merge.

**Comment by khaes-kth** [comment]
Per our discussion, @algomaster99 will test this option in Renovate config file on a separate repo to see if it works. Then, we'll merge it.

**Comment by algomaster99** [comment]
@khaes-kth I tried reproducing it on my [own repository](https://github.com/algomaster99/test-renovate) but somehow the bot is not running there. I cannot find any relevant resources which would help me _force_ its execution.

One alternative is to self-host renovate by installing Renovate-CLI on my local machine but I don't think that's worth our time. Let's try merging this PR?

**Review by khaes-kth — APPROVED** [review]

**Comment by khaes-kth** [comment]
Fine. Let's trust [this comment](https://github.com/renovatebot/config-help/issues/123#issuecomment-439618866). If we see Renovate is not working as expected, we can fix it again later.

**Comment by algomaster99** [comment]
@khaes-kth the bot autoclosed PRs which we wanted to get rid of. For example, https://github.com/SpoonLabs/sorald/pull/622.

**Comment by khaes-kth** [comment]
> @khaes-kth the bot autoclosed PRs which we wanted to get rid of. For example, #622.

Cool!

**Pull request merged**
