### PR TITLE
doc: Update CONTRIBUTING.md with PR guidelines

### LINKED ISSUE #235: Merging guidelines for maintainers
We're merging inconsistently right now. Most merges are squashed, but  not all. Sometimes the commit message prefix (i.e. fix, feat, etc) is preserved, and sometimes it isn't. We need to agree on a practice. I suggest the following.

1. Squash all PRs. It's just more practical. For example, I just now wanted to revert a feature that turned out to be severely flawed, but the PR wasn't squashed and so I couldn't easily do that.
2. Preserve any prefixes to the PRs in the squash message (e.g. feat, fix etc). These both make it easier to browse the commit history, and can be used for automatically generating release notes.

Does anyone have anything to add or change? Can we agree on these practices?

### PR DESCRIPTION
**Pull request by slarse**
Fix #235 

Just putting our discussion in #235 into writing in the repo. To be discussed during the meeting on the 25th.

### CODE REVIEW

**Comment by fermadeiral** [comment]
@slarse, maybe the guidelines should also contain something about PR with related issues. For example, it could be important to start the PR like you just started this one, so that the issue will be automatically closed once this PR gets merged. WDYT?

**Comment by slarse** [comment]
@fermadeiral Agreed! I'll add it.

**Comment by slarse** [comment]
@monperrus @fermadeiral @khaes-kth @nharrand Oh no, we were supposed to discuss the contributing guidelines during the meeting, I totally forgot! Just have a look at this PR and see if there's something you'd like to add, change or remove.

There's no rush at all with this, I'll bring it up next meeting if the PR isn't merged by then :)

**Comment by fermadeiral** [comment]
LGTM.

**Comment by monperrus** [comment]
LGTM

**Comment by khaes-kth** [comment]
LGTM as well.

**Comment by monperrus** [comment]
Thanks @slarse

**Pull request merged**
