### PR TITLE
fix: Check for flow breaks before patching with the repair for S2142

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes: #599

### CODE REVIEW

**Comment by khaes-kth** [comment]
Thanks a lot @algomaster99 . Seems to be fine.

Have you tried it on the commit I had referred to in #599 to see if it fixes the problem?

**Comment by algomaster99** [comment]
I don't see any commit linked in that issue. There is a code block which describes the bug and I have created tests similar to it. Could you please link the commit?

**Comment by khaes-kth** [comment]
Oh! You're right. I'll find the commit and send you the link.

**Comment by khaes-kth** [comment]
I found it. You get that error on `joelittlejohn/embedmongo-maven-plugin`, commit `72b45f438a69c6ae575aa62c6a536a35905ef7b8`.

**Comment by algomaster99** [comment]
Yes, it works now! This is [the line](https://github.com/joelittlejohn/embedmongo-maven-plugin/blob/72b45f438a69c6ae575aa62c6a536a35905ef7b8/src/main/java/com/github/joelittlejohn/embedmongo/StartMojo.java#L209) for future reference.

**Review by khaes-kth — APPROVED** [review]

**Comment by khaes-kth** [comment]
Thanks @algomaster99

**Comment by monperrus** [comment]
great start @algomaster99

**Pull request merged**
