### PR TITLE
refactor: store excluded references in a set which wraps `IdentityHashMap`

### PR DESCRIPTION
**Pull request by algomaster99**
Reference #602 

I thought I would refactor the code first as suggested by @slarse. 

> Just glancing at that code I would begin with wrapping that map in a set (with Collections.newSetFromMap), because the values aren't used :)

### CODE REVIEW

**Comment by algomaster99** [comment]
I am not sure what went wrong here, because tests passed on my machine. @khaes-kth could you please re-run the workflow? I think the failure could be because of the flaky tests.

**Comment by slarse** [comment]
@algomaster99 The scheduled builds on master have been failing for a few days, it's probably not related to this PR.

**Comment by khaes-kth** [comment]
>  @khaes-kth could you please re-run the workflow? I think the failure could be because of the flaky tests.

I did it, but it seems the problem isn't fix with a rerun. 

@fermadeiral @monperrus : can you add @algomaster99  as a collaborator so that he can see the logs? It seems I do not have access to do it.

**Comment by monperrus** [comment]
Aman and you now have role "maintainer".

**Comment by algomaster99** [comment]
> I did it, but it seems the problem isn't fix with a rerun.

The scheduled builds are failing as pointed out by Simon. I have created [a PR](https://github.com/INRIA/spoon/pull/4272) to fix it, but it seems like that isn't the best way.

**Comment by algomaster99** [comment]
The tests should pass here after #617 is merged.

**Comment by algomaster99** [comment]
@khaes-kth once all tests are green, you may proceed to merge. This PR just refactors the code and it doesn't fix anything.

**Comment by algomaster99** [comment]
@khaes-kth ping for merge.

**Review by khaes-kth — APPROVED** [review]
LGTM!

**Pull request merged**
