### PR TITLE
chore: Switch to Java 11

### LINKED ISSUE #211: switch to Java 11

### PR DESCRIPTION
**Pull request by slarse**
Fix #211 

We're dropping support for Java 8 and now only support Java 11+. This PR updates the pom and related documentation.

### CODE REVIEW

**Comment by khaes-kth** [comment]
Hi @slarse 

Thanks for the quick PR. Is this ready to be merged?

**Comment by slarse** [comment]
@khaes-kth yes, any PR where I put the "ready-for-review" label is also ready to be merged

**Comment by khaes-kth** [comment]
> @khaes-kth yes, any PR where I put the "ready-for-review" label is also ready to be merged

Great! Merged.

**Comment by slarse** [comment]
Thanks! I'm so happy to be able to use Java 11 features :)

**Pull request merged**
