### PR TITLE
WIP: feat: create api module (#758)

### PR DESCRIPTION
**Pull request by MartinWitt**
This PR is heavy WIP. It splits Sorald in Sorald core and an API module. Currently, this PR exists to test the CI and finish the movement. There are still classes in the wrong place.

### CODE REVIEW

**Comment by algomaster99** [comment]
It is so daunting to review this PR :open_mouth:

**Comment by MartinWitt** [comment]
Yeah, this is kind of a problem if you move so many files. We have to create a parent pom, move sorald to a submodule and move files from the sorald submodule to a new submodule. I could try splitting this in:
1. Creating the parent pom
2. Move Sorald to a submodule
3. Move parts of sorald to an api module.
Would this help you?

**Comment by algomaster99** [comment]
If splitting is convenient and does not take too much of your time, please consider it. :smile:

**Comment by MartinWitt** [comment]
Okay, I found an easier to review alternative, see #776

**Pull request closed without merging**
